name: transfer-dev-to-external-repo
on:
  push:
    branches:
      - dev

jobs:
  copy-to-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch ğŸ›ï¸
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        ref: dev
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    - name: Install and Build ğŸ”§ 
      run: pip install nbconvert==5.6.1 jupyter-book==0.6.3 && jupyter-book build ./docs --overwrite
    - run: ls -alhR 
    - name: Install SSH Client ğŸ”‘
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BASE_BRANCH: dev #The branch of this repository which should be transfered from.
        REPOSITORY_NAME: FAIRplus/cookbook-dev # The repository on github.com to which will be deployed = pushed.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
        
