name: transfer-dev-to-external-repo
on:
  push:
    branches:
      - dev

jobs:
  copy-to-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch ğŸ›ï¸
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        ref: dev
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    - name: Install and Build ğŸ”§ 
      run: pip install jupyter-book && jupyter-book build ./docs --overwrite
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        BASE_BRANCH: dev
        REPOSITORY_NAME: FAIRplus/cookbook-dev
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ./docs/_build # The folder the action should deploy.
        
